/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAttributeGroupsRouteImport } from './routes/api/attribute-groups'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BeneficiosIndexRouteImport } from './routes/beneficios/index'
import { Route as BeneficiosBenefitIdRouteImport } from './routes/beneficios/$benefitId'
import { Route as VideoIndexRouteImport } from './routes/video/index'
import { Route as ApiSignalsRegistryRouteImport } from './routes/api/signals/registry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttributeGroupsRoute = ApiAttributeGroupsRouteImport.update({
  id: '/api/attribute-groups',
  path: '/api/attribute-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosIndexRoute = BeneficiosIndexRouteImport.update({
  id: '/beneficios/',
  path: '/beneficios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosBenefitIdRoute = BeneficiosBenefitIdRouteImport.update({
  id: '/beneficios/$benefitId',
  path: '/beneficios/$benefitId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRegistryRoute = ApiSignalsRegistryRouteImport.update({
  id: '/api/signals/registry',
  path: '/api/signals/registry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/api/attribute-groups': typeof ApiAttributeGroupsRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficios/$benefitId': typeof BeneficiosBenefitIdRoute
  '/beneficios/': typeof BeneficiosIndexRoute
  '/video/': typeof VideoIndexRoute
  '/api/signals/registry': typeof ApiSignalsRegistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/api/attribute-groups': typeof ApiAttributeGroupsRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficios/$benefitId': typeof BeneficiosBenefitIdRoute
  '/beneficios': typeof BeneficiosIndexRoute
  '/video': typeof VideoIndexRoute
  '/api/signals/registry': typeof ApiSignalsRegistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/api/attribute-groups': typeof ApiAttributeGroupsRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficios/$benefitId': typeof BeneficiosBenefitIdRoute
  '/beneficios/': typeof BeneficiosIndexRoute
  '/video/': typeof VideoIndexRoute
  '/api/signals/registry': typeof ApiSignalsRegistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta'
    | '/login'
    | '/api/attribute-groups'
    | '/api/chat'
    | '/beneficios/$benefitId'
    | '/beneficios/'
    | '/video/'
    | '/api/signals/registry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/login'
    | '/api/attribute-groups'
    | '/api/chat'
    | '/beneficios/$benefitId'
    | '/beneficios'
    | '/video'
    | '/api/signals/registry'
  id:
    | '__root__'
    | '/'
    | '/cuenta'
    | '/login'
    | '/api/attribute-groups'
    | '/api/chat'
    | '/beneficios/$benefitId'
    | '/beneficios/'
    | '/video/'
    | '/api/signals/registry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuentaRoute: typeof CuentaRoute
  LoginRoute: typeof LoginRoute
  ApiAttributeGroupsRoute: typeof ApiAttributeGroupsRoute
  ApiChatRoute: typeof ApiChatRoute
  BeneficiosBenefitIdRoute: typeof BeneficiosBenefitIdRoute
  BeneficiosIndexRoute: typeof BeneficiosIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
  ApiSignalsRegistryRoute: typeof ApiSignalsRegistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attribute-groups': {
      id: '/api/attribute-groups'
      path: '/api/attribute-groups'
      fullPath: '/api/attribute-groups'
      preLoaderRoute: typeof ApiAttributeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios/': {
      id: '/beneficios/'
      path: '/beneficios'
      fullPath: '/beneficios/'
      preLoaderRoute: typeof BeneficiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios/$benefitId': {
      id: '/beneficios/$benefitId'
      path: '/beneficios/$benefitId'
      fullPath: '/beneficios/$benefitId'
      preLoaderRoute: typeof BeneficiosBenefitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals/registry': {
      id: '/api/signals/registry'
      path: '/api/signals/registry'
      fullPath: '/api/signals/registry'
      preLoaderRoute: typeof ApiSignalsRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuentaRoute: CuentaRoute,
  LoginRoute: LoginRoute,
  ApiAttributeGroupsRoute: ApiAttributeGroupsRoute,
  ApiChatRoute: ApiChatRoute,
  BeneficiosBenefitIdRoute: BeneficiosBenefitIdRoute,
  BeneficiosIndexRoute: BeneficiosIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
  ApiSignalsRegistryRoute: ApiSignalsRegistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
